-d C:\Users\admin\Desktop\Serv_UART_Gowin\impl\gwsynthesis\Serv_UART_Gowin.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\admin\Desktop\Serv_UART_Gowin\src\Serv_UART_Gowin.cst
-cfg C:\Users\admin\Desktop\Serv_UART_Gowin\impl\pnr\device.cfg
-sdc C:\Users\admin\Desktop\Serv_UART_Gowin\src\timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
